export const countriesWithImg = [
    { name: "United States", flagUrl: "https://flagcdn.com/w320/us.png" },
    { name: "Germany", flagUrl: "https://flagcdn.com/w320/de.png" },
    { name: "Vietnam", flagUrl: "https://flagcdn.com/w320/vn.png" },
    { name: "Canada", flagUrl: "https://flagcdn.com/w320/ca.png" },
    { name: "United Kingdom", flagUrl: "https://flagcdn.com/w320/gb.png" },
    { name: "Australia", flagUrl: "https://flagcdn.com/w320/au.png" },
    { name: "Brazil", flagUrl: "https://flagcdn.com/w320/br.png" },
    { name: "France", flagUrl: "https://flagcdn.com/w320/fr.png" },
    { name: "India", flagUrl: "https://flagcdn.com/w320/in.png" },
    { name: "Italy", flagUrl: "https://flagcdn.com/w320/it.png" },
    { name: "Russia", flagUrl: "https://flagcdn.com/w320/ru.png" },
    { name: "China", flagUrl: "https://flagcdn.com/w320/cn.png" },
    { name: "Japan", flagUrl: "https://flagcdn.com/w320/jp.png" },
    { name: "Mexico", flagUrl: "https://flagcdn.com/w320/mx.png" },
    { name: "Spain", flagUrl: "https://flagcdn.com/w320/es.png" },
    { name: "South Korea", flagUrl: "https://flagcdn.com/w320/kr.png" },
    { name: "Argentina", flagUrl: "https://flagcdn.com/w320/ar.png" },
    { name: "Saudi Arabia", flagUrl: "https://flagcdn.com/w320/sa.png" },
    { name: "South Africa", flagUrl: "https://flagcdn.com/w320/za.png" },
    { name: "Egypt", flagUrl: "https://flagcdn.com/w320/eg.png" },
    { name: "Turkey", flagUrl: "https://flagcdn.com/w320/tr.png" },
    { name: "Nigeria", flagUrl: "https://flagcdn.com/w320/ng.png" },
    { name: "Indonesia", flagUrl: "https://flagcdn.com/w320/id.png" },
    { name: "Pakistan", flagUrl: "https://flagcdn.com/w320/pk.png" },
    { name: "Poland", flagUrl: "https://flagcdn.com/w320/pl.png" },
    { name: "Chile", flagUrl: "https://flagcdn.com/w320/cl.png" },
    { name: "Thailand", flagUrl: "https://flagcdn.com/w320/th.png" },
    { name: "Sweden", flagUrl: "https://flagcdn.com/w320/se.png" },
    { name: "Finland", flagUrl: "https://flagcdn.com/w320/fi.png" },
    { name: "Belgium", flagUrl: "https://flagcdn.com/w320/be.png" },
    { name: "Switzerland", flagUrl: "https://flagcdn.com/w320/ch.png" },
    { name: "Norway", flagUrl: "https://flagcdn.com/w320/no.png" },
    { name: "Netherlands", flagUrl: "https://flagcdn.com/w320/nl.png" },
    { name: "Denmark", flagUrl: "https://flagcdn.com/w320/dk.png" },
    { name: "Portugal", flagUrl: "https://flagcdn.com/w320/pt.png" },
    { name: "Greece", flagUrl: "https://flagcdn.com/w320/gr.png" },
    { name: "Ireland", flagUrl: "https://flagcdn.com/w320/ie.png" },
    { name: "Austria", flagUrl: "https://flagcdn.com/w320/at.png" },
    { name: "New Zealand", flagUrl: "https://flagcdn.com/w320/nz.png" },
    { name: "Israel", flagUrl: "https://flagcdn.com/w320/il.png" },
    { name: "Poland", flagUrl: "https://flagcdn.com/w320/pl.png" },
    { name: "Romania", flagUrl: "https://flagcdn.com/w320/ro.png" },
    { name: "Ukraine", flagUrl: "https://flagcdn.com/w320/ua.png" },
    { name: "Czech Republic", flagUrl: "https://flagcdn.com/w320/cz.png" },
    { name: "Hungary", flagUrl: "https://flagcdn.com/w320/hu.png" },
    { name: "Slovakia", flagUrl: "https://flagcdn.com/w320/sk.png" },
    { name: "Bulgaria", flagUrl: "https://flagcdn.com/w320/bg.png" },
    { name: "Croatia", flagUrl: "https://flagcdn.com/w320/hr.png" },
    { name: "Serbia", flagUrl: "https://flagcdn.com/w320/rs.png" },
    { name: "Slovenia", flagUrl: "https://flagcdn.com/w320/si.png" },
    { name: "Luxembourg", flagUrl: "https://flagcdn.com/w320/lu.png" },
    { name: "Estonia", flagUrl: "https://flagcdn.com/w320/ee.png" },
    { name: "Latvia", flagUrl: "https://flagcdn.com/w320/lv.png" },
    { name: "Lithuania", flagUrl: "https://flagcdn.com/w320/lt.png" },
    { name: "Belarus", flagUrl: "https://flagcdn.com/w320/by.png" },
    { name: "Georgia", flagUrl: "https://flagcdn.com/w320/ge.png" },
    { name: "Moldova", flagUrl: "https://flagcdn.com/w320/md.png" },
    { name: "Armenia", flagUrl: "https://flagcdn.com/w320/am.png" },
    { name: "Azerbaijan", flagUrl: "https://flagcdn.com/w320/az.png" },
    { name: "Kazakhstan", flagUrl: "https://flagcdn.com/w320/kz.png" },
    { name: "Kyrgyzstan", flagUrl: "https://flagcdn.com/w320/kg.png" },
    { name: "Tajikistan", flagUrl: "https://flagcdn.com/w320/tj.png" },
    { name: "Turkmenistan", flagUrl: "https://flagcdn.com/w320/tm.png" },
    { name: "Uzbekistan", flagUrl: "https://flagcdn.com/w320/uz.png" },
    { name: "Afghanistan", flagUrl: "https://flagcdn.com/w320/af.png" },
    { name: "Sri Lanka", flagUrl: "https://flagcdn.com/w320/lk.png" },
    { name: "Nepal", flagUrl: "https://flagcdn.com/w320/np.png" },
    { name: "Bhutan", flagUrl: "https://flagcdn.com/w320/bt.png" },
    { name: "Maldives", flagUrl: "https://flagcdn.com/w320/mv.png" },
    { name: "Myanmar", flagUrl: "https://flagcdn.com/w320/mm.png" },
    { name: "Bangladesh", flagUrl: "https://flagcdn.com/w320/bd.png" },
    { name: "Malaysia", flagUrl: "https://flagcdn.com/w320/my.png" },
    { name: "Singapore", flagUrl: "https://flagcdn.com/w320/sg.png" },
    { name: "Brunei", flagUrl: "https://flagcdn.com/w320/bn.png" },
    { name: "Cambodia", flagUrl: "https://flagcdn.com/w320/kh.png" },
    { name: "Laos", flagUrl: "https://flagcdn.com/w320/la.png" },
    { name: "Philippines", flagUrl: "https://flagcdn.com/w320/ph.png" },
    { name: "Indonesia", flagUrl: "https://flagcdn.com/w320/id.png" },
    { name: "Timor-Leste", flagUrl: "https://flagcdn.com/w320/tl.png" },
    { name: "Palau", flagUrl: "https://flagcdn.com/w320/pw.png" },
    { name: "Fiji", flagUrl: "https://flagcdn.com/w320/fj.png" },
    { name: "Vanuatu", flagUrl: "https://flagcdn.com/w320/vu.png" },
    { name: "Samoa", flagUrl: "https://flagcdn.com/w320/ws.png" },
    { name: "Tonga", flagUrl: "https://flagcdn.com/w320/to.png" },
    { name: "Solomon Islands", flagUrl: "https://flagcdn.com/w320/sb.png" },
    { name: "Micronesia", flagUrl: "https://flagcdn.com/w320/fm.png" },
    { name: "Kiribati", flagUrl: "https://flagcdn.com/w320/ki.png" },
    { name: "Marshall Islands", flagUrl: "https://flagcdn.com/w320/mh.png" },
    { name: "Nauru", flagUrl: "https://flagcdn.com/w320/nr.png" },
    { name: "Tuvalu", flagUrl: "https://flagcdn.com/w320/tv.png" },
    { name: "Tonga", flagUrl: "https://flagcdn.com/w320/to.png" },
    { name: "Seychelles", flagUrl: "https://flagcdn.com/w320/sc.png" },
    { name: "Comoros", flagUrl: "https://flagcdn.com/w320/km.png" },
    { name: "Mauritius", flagUrl: "https://flagcdn.com/w320/mu.png" },
    { name: "Reunion", flagUrl: "https://flagcdn.com/w320/re.png" },
    { name: "Mayotte", flagUrl: "https://flagcdn.com/w320/yt.png" },
    { name: "Saint Pierre and Miquelon", flagUrl: "https://flagcdn.com/w320/pm.png" }
  ];
  
  export const getCountries = () => {
    return countriesWithImg;
  };