const RouteNames = {
  HOME: "/home",
  EVENTS: "/events",
  LOGIN: "/login",
  REGISTER: "/register",
  FORGOT_PASSWORD: "/forgot-password",
  GOOGLE: "/login-google",
  NOT_FOUND: "/not-found",
  ADMIN_DASHBOARD: "/admin/dashboard",
  STAFF_DASHBOARD: "/staff/dashboard",
  BLOG: "/blog",
  CART: "/cart",
  ACCOUNT: "/account",
  ACCOUNT_APPOINTMENTS: "/account/appointments",
  ACCOUNT_ORDERS: "/account/orders",
  ACCOUNT_CHANGE_PASSWORD: "/account/change-password",
  PAYMENT: "/cart/payment",
  BILLING: "/admin/billing",
  ADMIN_HOME: "/admin/dashboard",
  ADMIN_PROFILE: "/admin/profile",
  ADMIN_RTL: "/admin/rtl",
  ADMIN_SIGNIN: "/admin/sign-in",
  ADMIN_SIGNUP: "/admin/sign-up",
  ADMIN_CUSTOMER_MANAGEMENT: "/admin/customer-management",
  SKINCARE_QUIZ_MANAGEMENT: "/admin/skincare-quiz-management",
  STAFF_MANAGEMENT: "/admin/staff-management",
  STAFF_DETAIL: "/admin/staff-management/:id",
  BLOG_MANAGEMENT: "/admin/blog-management",
  BLOG_DETAILS: "blog-details/:id",
  PAYMENT_SUCCESS: "/payment-success",
  PAYMENT_FAILED: "/payment-failed",
  PAYMENT_ERROR: "/payment-error",
  PAYMENT_RETURN: "/vnpay-return",
  PAYMENT_NOT_FOUND: "/payment-not-found",
  ORDERS: "/admin/orders",
  CUSTOMERS: "/admin/customers",
  FEEDBACK_MANAGEMENT: "/admin/feedback-management",
  VACCINE_PACKAGE: "/vaccine-package",
  VACCINE_MANAGEMENT: "/admin/vaccine-management",
  VACCINE_DETAIL_MANAGEMENT: "/admin/vaccine-management/:id",
  VACCINE_PACKAGE_MANAGEMENT: "/admin/vaccine-package-management",
  VACCINE_PACKAGE_DETAIL_MANAGEMENT: "/admin/vaccine-package-management/:id",
  VACCINE_SCHEDULE: "/admin/vaccine-schedule",
  VACCINE_LIST: "/vaccine-list",
  VACCINE_DETAIL: "/vaccine-detail/:id",
  PROFESSIONAL_TEAM: "/professional-team",
  APPOINTMENT_MANAGEMENT: "/admin/appointment-management",
  VACCINE_CATEGORY_MANAGEMENT: "/admin/vaccine-category-management",
  STAFF_SHIFT_PAGE:"/staff/shift",
  STAFF_SCHEDULE_MANAGEMENT:"/admin/staff-schedule-management",
  PROFESSIONAL_TEAM_DETAILS: "/professional-team/:id",
  STAFF_PROFILE: "/staff/profile"
};

export default RouteNames;
