const RouteNames = {
  HOME: "/home",
  EVENTS: "/events",
  LOGIN: "/login",
  REGISTER: "/register",
  FORGOT_PASSWORD: "/forgot-password",
  GOOGLE: "/login-google",
  NOT_FOUND: "/not-found",
  ADMIN_DASHBOARD: "/admin/dashboard",
  STAFF_DASHBOARD: "/staff/dashboard",
  BEAUTY_BLOG: "/beauty-blog",
  CART: "/cart",
  ACCOUNT: "/account",
  ACCOUNT_ORDERS: "/account/orders",
  ACCOUNT_CHANGE_PASSWORD: "/account/change-password",
  PAYMENT: "/cart/payment",
  BILLING: "/admin/billing",
  ADMIN_HOME: "/admin/dashboard",
  ADMIN_PROFILE: "/admin/profile",
  ADMIN_RTL: "/admin/rtl",
  ADMIN_SIGNIN: "/admin/sign-in",
  ADMIN_SIGNUP: "/admin/sign-up",
  ADMIN_CUSTOMER_MANAGEMENT: "/admin/customer-management",
  SKINCARE_QUIZ_MANAGEMENT: "/admin/skincare-quiz-management",
  STAFF_MANAGEMENT: "/admin/staff-management",
  STAFF_DETAIL: "/admin/staff-management/:id",
  VACCINE_MANAGEMENT: "/admin/vaccine-management",
  VACCINE_DETAIL: "/admin/vaccine-management/:id",
  PACKAGE_MANAGEMENT: "/admin/package-management",
  BLOG_MANAGEMENT: "/admin/blog-management",
  BLOG_DETAILS: "blog-details/:id",
  PAYMENT_SUCCESS: "/payment-success",
  PAYMENT_FAILED: "/payment-failed",
  PAYMENT_ERROR: "/payment-error",
  PAYMENT_RETURN: "/vnpay-return",
  PAYMENT_NOT_FOUND: "/payment-not-found",
  ORDERS: "/admin/orders",
  VACCINE_SCHEDULE: "/admin/vaccine-schedule",
  CUSTOMERS: "/admin/customers",
};

export default RouteNames;
